version: '3'

name: umarv-ros1

services:
  umarv-ros1:
    container_name: umarv-ros1
    image: ros-noetic-desktop-full
    build: ../
    hostname: umarv-ros1
    environment:
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PULSE_SERVER: ${PULSE_SERVER}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl
      - ../ws:/home/umarv/ws
    devices:
      - /dev/dxg:/dev/dxg
      # - /dev/ttyUSB0:/dev/ttyUSB0
      # - /dev/dri/card0:/dev/dri/card0
      # - /dev/dri/renderD128:/dev/dri/renderD128
    tty: true
