version: '3'

name: umarv-ros2

services:
  umarv-ros2:
    container_name: umarv-ros2
    image: ros-humble-desktop-full
    build: ../
    hostname: umarv-ros2
    environment:
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PULSE_SERVER: ${PULSE_SERVER}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl
      - ../ws:/home/umarv/ws
    devices:
      - /dev/dxg:/dev/dxg
    tty: true
